kind: project
metadata:
  name: gitproject-xingsheng
spec:
  functions:
  - url: src/job_func.py
    name: myjob
    kind: job
    image: mlrun/mlrun
    handler: src.job_func.job_handler
    with_repo: true
  - name: nuclio
    kind: nuclio
    image: mlrun/mlrun
    handler: nuclio_func:nuclio_handler
    with_repo: true
  - url: serving.yaml
    name: serving
    with_repo: true
  workflows: []
  artifacts: []
  conda: ''
  source: git://github.com/xsqian/project-archive.git#refs/heads/main
  origin_url: git://github.com/xsqian/project-archive.git#refs/heads/main
  desired_state: online
  build:
    commands: []
    requirements: []
  custom_packagers: []
