kind: project
metadata:
  name: git-proj-xingsheng
  created: '2023-10-27T03:02:18.069000'
spec:
  description: my new project
  functions:
  - url: src/job_func.py
    name: myjob
    kind: job
    image: mlrun/mlrun
    handler: job_func.job_handler
    with_repo: true
  - name: nuclio
    kind: nuclio
    image: mlrun/mlrun
    handler: nuclio_func:nuclio_handler
    with_repo: true
  - url: serving.yaml
    name: serving
    with_repo: true
  workflows: []
  artifacts: []
  conda: ''
  source: git://github.com/xsqian/project-archive.git#refs/heads/main
  origin_url: git://github.com/xsqian/project-archive.git#refs/heads/main
  load_source_on_run: true
  desired_state: online
  build:
    commands: []
    requirements: []
  custom_packagers: []
status:
  state: online
